name: Automated XPI Builder
on: [push]

jobs: 
 build:
  runs-on: ubuntu-latest  
  steps: 
    - name: Checkout code 
      uses: actions/checkout@master

    - name: Automated XPI build process
      uses: TheDoctor0/zip-release@0.7.6
      with:

        filename: nightly-release.xpi
        type: 'zip'

        exclusions: '*.git* *.ps1* /*gre-resources/* /*other-tools-and-tests/* /*archive-worker-directory/* .editorconfig'
        directory: .
        path: .
    - name: Nightly-Alpha-Publish
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "none"
        ALLOW_TAG_PREFIX: "true"
      with:
        args: |
            nightly-release.xpi
