name: Automated XPI Builder
on: [push]

jobs: 
 build:
  runs-on: ubuntu-latest  
  steps: 
    - name: Checkout code 
      uses: actions/checkout@master

    - name: Automated XPI build process
      uses: TheDoctor0/zip-release@0.7.6
      with:

        filename: nightly-release.xpi
        type: 'zip'

        exclusions: '*.git* *.ps1* /*gre-resources/* /*other-tools-and-tests/* .editorconfig'
        directory: .
        path: .
